import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}) {
  return (
    <html>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Aladin&display=swap" rel="stylesheet"/>
        <link id="theme-link" rel="stylesheet" href="/themes/lara-light-blue/theme.css"></link>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Andada+Pro&family=Poppins:wght@100&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <div className="bg-gradient-to-br from-[#F6F6F5] to-[#CAD2C5] h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
